export enum StateStageEnum {
  IDLE = 'IDLE',
  EXPENSES_DESCRIPTION = 'EXPENSES_DESCRIPTION',
  EXPENSES_AMOUNT = 'EXPENSES_AMOUNT',
  EXPENSES_CATEGORY = 'EXPENSES_CATEGORY',
  INCOME_DESCRIPTION = 'INCOME_DESCRIPTION',
  INCOME_AMOUNT = 'INCOME_AMOUNT',
  INCOME_CATEGORY = 'INCOME_CATEGORY',
}
